const mongoose = require('mongoose');
const dotenv = require('dotenv');
dotenv.config();
const Event = require('./Models/Event.js');

const events = [
    // ==========================================
    // MAHARASHTRA DISTRICT PRODUCTS (ODOP) - 36 Districts
    // ==========================================

    {
        title: "Ahmednagar Jaggery",
        description: "Pure, high-quality sugarcane jaggery known for its natural sweetness.",
        date: new Date(),
        location: "Ahmednagar, Maharashtra",
        category: "Agriculture",
        totalAmount: 10000,
        availableAmount: 8000,
        productPrice: 60,
        image: "https://images.jdmagicbox.com/v2/comp/def_content/ncat_id/jaggery-u9yxehc-250.jpg",
    },
    {
        title: "Akola Cotton",
        description: "Premium quality raw cotton fibers from the cotton belt of Maharashtra.",
        date: new Date(),
        location: "Akola, Maharashtra",
        category: "Agriculture",
        totalAmount: 50000,
        availableAmount: 40000,
        productPrice: 150,
        image: "https://images.jdmagicbox.com/v2/comp/def_content/ncat_id/cotton-dk3zezh-250.jpg",
    },
    {
        title: "Amravati Mandarin Oranges",
        description: "Juicy and tangy Mandarin oranges freshly harvested from local orchards.",
        date: new Date(),
        location: "Amravati, Maharashtra",
        category: "Agriculture",
        totalAmount: 20000,
        availableAmount: 15000,
        productPrice: 80,
        image: "https://content.jdmagicbox.com/quickquotes/images_main/vitamin-c-rich-orange-fruit-802767833-zul9c2kb.jpg?impolicy=queryparam&im=Resize=(360,360),aspect=fit",
    },
    {
        title: "Aurangabad Paithani Sarees",
        description: "Exquisite handwoven silk sarees with pure gold zari borders and pallu.",
        date: new Date(),
        location: "Aurangabad, Maharashtra",
        category: "Handloom",
        totalAmount: 100,
        availableAmount: 50,
        productPrice: 15000,
        image: "https://houseofhind.com/cdn/shop/articles/Untitled-1_1800x1800_be791027-99df-4f97-bbec-a4cb767a6eab.webp?v=1736009146",
    },
    {
        title: "Beed Custard Apple",
        description: "Sweet, creamy, and large custard apples (Sitaphal) natively grown.",
        date: new Date(),
        location: "Beed, Maharashtra",
        category: "Agriculture",
        totalAmount: 5000,
        availableAmount: 4000,
        productPrice: 100,
        image: "https://5.imimg.com/data5/ANDROID/Default/2020/9/RX/UG/JO/42827488/product-jpeg.jpeg",
    },
    {
        title: "Bhandara Tumsar Rice",
        description: "High-quality fragrant rice produced in the Rice Bowl of Maharashtra.",
        date: new Date(),
        location: "Bhandara, Maharashtra",
        category: "Agriculture",
        totalAmount: 25000,
        availableAmount: 20000,
        productPrice: 70,
        image: "https://5.imimg.com/data5/SELLER/Default/2021/7/UQ/BC/ON/113060825/rice-jpg-500x500.jpg",
    },
    {
        title: "Buldhana Soyabean",
        description: "Protein-rich soybeans cultivated efficiently by local farmers.",
        date: new Date(),
        location: "Buldhana, Maharashtra",
        category: "Agriculture",
        totalAmount: 30000,
        availableAmount: 25000,
        productPrice: 45,
        image: "https://www.agroexporters.net/uploaded-files/thumb-cache/member_127/thumb---soyabean_5009.jpg",
    },
    {
        title: "chandrapur bamboo",
        description: "Handmade eco-friendly bamboo furniture, mats, and decorative items.",
        date: new Date(),
        location: "Chandrapur, Maharashtra",
        category: "Handicraft",
        totalAmount: 500,
        availableAmount: 350,
        productPrice: 400,
        image: "https://nurserynisarga.in/wp-content/uploads/2023/04/gg.webp",
    },
    {
        title: "Dhule Chilli",
        description: "Spicy and vibrant red chillies used widely for spices and exports.",
        date: new Date(),
        location: "Dhule, Maharashtra",
        category: "Agriculture",
        totalAmount: 15000,
        availableAmount: 12000,
        productPrice: 200,
        image: "https://images.jdmagicbox.com/v2/comp/def_content/ncat_id/chilli-powder-mpqv2g9-250.jpg",
    },
    {
        title: "Gadchiroli Forest Honey",
        description: "Pure, wild, and organic forest honey collected by tribal communities.",
        date: new Date(),
        location: "Gadchiroli, Maharashtra",
        category: "Forest Produce",
        totalAmount: 800,
        availableAmount: 650,
        productPrice: 350,
        image: "https://thepurelydesi.com/cdn/shop/files/WhatsAppImage2026-04-08at4.09.01PM_4.jpg?v=1775731474",
    },
    {
        title: "Gondia Rice",
        description: "Premium fine-grain rice sourced from local paddy fields.",
        date: new Date(),
        location: "Gondia, Maharashtra",
        category: "Agriculture",
        totalAmount: 20000,
        availableAmount: 15000,
        productPrice: 65,
        image: "https://feeds.abplive.com/onecms/images/uploaded-images/2023/08/10/862050c00ffac727895dc37fe6fbb528169165977748919_original.jpg",
    },
    {
        title: "Hingoli Turmeric",
        description: "Aromatic turmeric with rich color and high medicinal value.",
        date: new Date(),
        location: "Hingoli, Maharashtra",
        category: "Agriculture",
        totalAmount: 10000,
        availableAmount: 8000,
        productPrice: 150,
        image: "https://5.imimg.com/data5/SELLER/Default/2024/12/472367226/ZT/DU/DR/98855679/dried-turmeric-finger-500x500.jpeg",
    },
    {
        title: "Jalgaon Banana",
        description: "Sweet, nutrient-rich GI-tagged bananas exported globally.",
        date: new Date(),
        location: "Jalgaon, Maharashtra",
        category: "Agriculture",
        totalAmount: 50000,
        availableAmount: 40000,
        productPrice: 35,
        image: "https://cpimg.tistatic.com/07443543/b/4/Fresh-Yellow-Banana.jpg",
    },
    {
        title: "Jalna Sweet Orange (Mosambi)",
        description: "Fresh and highly refreshing Mosambi fruits known for high juice content.",
        date: new Date(),
        location: "Jalna, Maharashtra",
        category: "Agriculture",
        totalAmount: 15000,
        availableAmount: 12000,
        productPrice: 90,
        image: "https://5.imimg.com/data5/SELLER/Default/2022/9/LI/VC/PU/47383834/new-product-250x250.jpeg",
    },
    {
        title: "Kolhapur Chappals",
        description: "Handcrafted, durable genuine leather traditional footwear.",
        date: new Date(),
        location: "Kolhapur, Maharashtra",
        category: "Handicraft",
        totalAmount: 1000,
        availableAmount: 750,
        productPrice: 1500,
        image: "https://www.korakari.com/cdn/shop/files/Men_3.webp?quality=75&v=1774930466&width=320",
    },
    {
        title: "Latur Tur Dal",
        description: "Nutritious and delicious split pigeon peas, a staple pulse.",
        date: new Date(),
        location: "Latur, Maharashtra",
        category: "Agriculture",
        totalAmount: 12000,
        availableAmount: 10000,
        productPrice: 140,
        image: "https://www.indianonshop.com/wp-content/uploads/2020/03/Chana-Dal.jpeg",
    },
    {
        title: "Mumbai City Textile Apparels",
        description: "Modern and traditional readymade garments from the textile hub.",
        date: new Date(),
        location: "Mumbai City, Maharashtra",
        category: "Textile",
        totalAmount: 5000,
        availableAmount: 3500,
        productPrice: 1200,
        image: "https://housing.com/news/wp-content/uploads/2023/09/top-10-textile-comapnies-in-india-f-compressed.jpg",
    },
    {
        title: "Mumbai Suburban Koli Seafood",
        description: "Freshly caught and dried seafood including Bombay Duck.",
        date: new Date(),
        location: "Mumbai Suburban, Maharashtra",
        category: "Food",
        totalAmount: 2000,
        availableAmount: 1500,
        productPrice: 500,
        image: "https://content.jdmagicbox.com/v2/comp/mumbai/m4/022pxx22.xx22.230824193737.v7m4/catalogue/versova-koli-sea-food-festival-2023-versova-mumbai-sea-food-restaurants-x6ubgd4wmg.jpg",
    },
    {
        title: "Nagpur Oranges",
        description: "World-famous sweet and tangy oranges grown in the orange city.",
        date: new Date(),
        location: "Nagpur, Maharashtra",
        category: "Agriculture",
        totalAmount: 30000,
        availableAmount: 25000,
        productPrice: 85,
        image: "https://4.imimg.com/data4/PC/LP/MY-24421102/nagpur-orange-500x500.jpg",
    },
    {
        title: "Nanded Cotton Fabrics",
        description: "Comfortable and durable woven cotton fabrics produced locally.",
        date: new Date(),
        location: "Nanded, Maharashtra",
        category: "Handloom",
        totalAmount: 4000,
        availableAmount: 3000,
        productPrice: 800,
        image: "https://www.shalvifashion.com/images/products/pure-cotton-fabric.jpg",
    },
    {
        title: "Nandurbar Navapur Tur Dal",
        description: "Highly sought-after protein-rich Tur Dal from Navapur.",
        date: new Date(),
        location: "Nandurbar, Maharashtra",
        category: "Agriculture",
        totalAmount: 8000,
        availableAmount: 6000,
        productPrice: 130,
        image: "https://www.agroexporters.net/uploaded-files/thumb-cache/member_127/thumb---organic-urad-dal_4952.jpg",
    },
    {
        title: "Nashik Grapes",
        description: "Premium quality table and wine grapes from the Wine Capital of India.",
        date: new Date(),
        location: "Nashik, Maharashtra",
        category: "Agriculture",
        totalAmount: 25000,
        availableAmount: 20000,
        productPrice: 90,
        image: "https://5.imimg.com/data5/SELLER/Default/2020/12/QZ/EM/OJ/119047533/nashik-capsule-grapes.jpg",
    },
    {
        title: "Osmanabad Handlooms",
        description: "Beautifully woven traditional textiles and garments.",
        date: new Date(),
        location: "Osmanabad, Maharashtra",
        category: "Handloom",
        totalAmount: 500,
        availableAmount: 400,
        productPrice: 2000,
        image: "https://images.jdmagicbox.com/v2/comp/paithan/p6/9999p2431.2431.181205152428.b6p6/catalogue/gopi-paithani-nx-wholsale-and-manufacturers-paithan-ho-paithan-banarasi-silk-saree-wholesalers-nw2x2up4dy.jpg",
    },
    {
        title: "Palghar Warli Painting",
        description: "Authentic tribal Warli art painted on canvas and home decor items.",
        date: new Date(),
        location: "Palghar, Maharashtra",
        category: "Handicraft",
        totalAmount: 1000,
        availableAmount: 850,
        productPrice: 500,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRd69yfR5IWFQ3st-HUBVYf-GZcbDYPXHjN5w&s",
    },
    {
        title: "Parbhani Jowar",
        description: "High-grade nutritious sorghum cultivated widely in the district.",
        date: new Date(),
        location: "Parbhani, Maharashtra",
        category: "Agriculture",
        totalAmount: 15000,
        availableAmount: 12000,
        productPrice: 40,
        image: "https://images.jdmagicbox.com/quickquotes/images_main/jowar-millet-sorghum-1kg-organic-and-unpolished-2024493616-0lxcxuka.jpg",
    },
    {
        title: "Pune Purandar Figs",
        description: "Sweet, highly nutritious fresh figs native to Purandar taluka.",
        date: new Date(),
        location: "Pune, Maharashtra",
        category: "Agriculture",
        totalAmount: 3000,
        availableAmount: 2500,
        productPrice: 250,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQjVcz27SRQ2n39_Dz8cyrZyj4IgCITKVpwmA&s",
    },
    {
        title: "Raigad Alibag White Onion",
        description: "Distinctively sweet and healthy GI-tagged white onions.",
        date: new Date(),
        location: "Raigad, Maharashtra",
        category: "Agriculture",
        totalAmount: 8000,
        availableAmount: 6000,
        productPrice: 60,
        image: "https://5.imimg.com/data5/VS/XT/ZR/SELLER-81389294/onion-white-250x250.jpg",
    },
    {
        title: "Ratnagiri Alphonso Mango",
        description: "The King of Mangoes, world-famous for its sweet taste and vibrant color.",
        date: new Date(),
        location: "Ratnagiri, Maharashtra",
        category: "Agriculture",
        totalAmount: 10000,
        availableAmount: 8000,
        productPrice: 1500,
        image: "https://royalsplant.com/wp-content/uploads/2024/05/11062b_012d6c9a50fe43e7be6de53eefc62657mv2.webp",
    },
    {
        title: "Sangli Turmeric",
        description: "Premium GI-tagged turmeric heavily traded in Sangli markets.",
        date: new Date(),
        location: "Sangli, Maharashtra",
        category: "Agriculture",
        totalAmount: 20000,
        availableAmount: 18000,
        productPrice: 180,
        image: "https://sahasa.in/wp-content/uploads/2020/12/sangli-turmeric-1-e1607406144725.jpg",
    },
    {
        title: "Satara Mahabaleshwar Strawberry",
        description: "Plump, red, and juicy GI-tagged strawberries from Mahabaleshwar hills.",
        date: new Date(),
        location: "Satara, Maharashtra",
        category: "Agriculture",
        totalAmount: 5000,
        availableAmount: 4000,
        productPrice: 300,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcROaTEj6ClFRLBn91cGQcrDDxhb9SLMougyDg&s",
    },
    {
        title: "Sindhudurg Cashew",
        description: "Top-quality roasted and salted cashew kernels from Konkan coast.",
        date: new Date(),
        location: "Sindhudurg, Maharashtra",
        category: "Agriculture",
        totalAmount: 4000,
        availableAmount: 3500,
        productPrice: 900,
        image: "https://tiimg.tistatic.com/fp/2/007/854/1-2-inches-size-salted-cashew-nuts-originated-in-brazil-157.jpg",
    },
    {
        title: "Solapuri Chaddar",
        description: "Comfortable, unique jacquard woven cotton blankets.",
        date: new Date(),
        location: "Solapur, Maharashtra",
        category: "Handloom",
        totalAmount: 2000,
        availableAmount: 1500,
        productPrice: 600,
        image: "https://tiimg.tistatic.com/fp/1/008/023/solapur-designer-printed-chaddar-425.jpg",
    },
    {
        title: "Thane Handicrafts",
        description: "Beautifully carved local wood and clay decorative products.",
        date: new Date(),
        location: "Thane, Maharashtra",
        category: "Handicraft",
        totalAmount: 1000,
        availableAmount: 800,
        productPrice: 500,
        image: "https://content.jdmagicbox.com/comp/def_content/handicraft-item-dealers/12b942b856-handicraft-item-dealers-3-pakm6.jpg",
    },
    {
        title: "Wardha Khadi",
        description: "Handspun and handwoven khadi garments reflecting Gandhian heritage.",
        date: new Date(),
        location: "Wardha, Maharashtra",
        category: "Handloom",
        totalAmount: 800,
        availableAmount: 650,
        productPrice: 900,
        image: "https://tiimg.tistatic.com/fp/1/007/786/lightweight-shrink-resistance-plain-white-and-brown-khadi-fabric-for-textile-industries-566.jpg",
    },
    {
        title: "Washim Soyabean",
        description: "High-yield organic soybeans, a major crop of the region.",
        date: new Date(),
        location: "Washim, Maharashtra",
        category: "Agriculture",
        totalAmount: 20000,
        availableAmount: 18000,
        productPrice: 48,
        image: "https://5.imimg.com/data5/SELLER/Default/2021/9/AO/HJ/SC/54141789/natural-soy-bean-250x250.jpg",
    },
    {
        title: "Yavatmal White Gold Cotton",
        description: "Long-staple raw cotton from the White Gold city of Maharashtra.",
        date: new Date(),
        location: "Yavatmal, Maharashtra",
        category: "Agriculture",
        totalAmount: 40000,
        availableAmount: 35000,
        productPrice: 160,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQzXIUMY43Lh6YfbwegdEHhHAWYFvkK1DeBQ&s",
    },
    // add new data on bihar
    {
        title: "Bags & Garments",
        description: "Champaran, with a significant number of small and medium-sized enterprises engaged in manufacturing",
        date: new Date(),
        location: "East Champaran (Motihari), Bihar",
        category: "ODOP Product",
        totalAmount: 100,
        availableAmount: 100,
        productPrice: 50,
        image: "https://static.india.gov.in/npiprod/odop/uploads/bags_and_garments_7b7eb1e8a9.jpg",
    },

    {
        title: "Bawan Booti",
        description: "Bawan Booti Sari, a fabric of great cultural significance, is woven with care and precision in the verdant fields of Nalanda, Bihar.",
        date: new Date(),
        location: "Nalanda, Bihar",
        category: "ODOP Product",
        totalAmount: 100,
        availableAmount: 100,
        productPrice: 500,
        image: "https://static.india.gov.in/npiprod/odop/uploads/bawan_booti_578d6bbba1.jpg",
    },

    {
        title: "Bhagalpuri Silk",
        description: "Famous Bhagalpuri silk fabric.",
        date: new Date(),
        location: "Bhagalpur, Bihar",
        category: "Textile",
        totalAmount: 80,
        availableAmount: 80,
        productPrice: 2000,
        image: "https://static.india.gov.in/npiprod/odop/uploads/bhagalpur_silk_2f4a78283d.png",
    },

    {
        title: "Mentha",
        description: "Mentha, a fragrant and versatile herb, is a prized produce of Siwan, Bihar.",
        date: new Date(),
        location: "Siwan, Bihar",
        category: "Textile Product",
        totalAmount: 100,
        availableAmount: 100,
        productPrice: 700,
        image: "https://static.india.gov.in/npiprod/odop/uploads/mentha_307af93265.jpg",
    },
    {
        title: "Bamboo Art",
        description: "Chhena Murki is a popular, dry Indian sweet made from Motihari, Bihar.",
        date: new Date(),
        location: "Samastipur, Bihar",
        category: "HandiCraft Product",
        totalAmount: 100,
        availableAmount: 100,
        productPrice: 200,
        image: "https://static.india.gov.in/npiprod/odop/uploads/bamboo_art_1e422027a3.jpg",
    },
    {
        title: "Bamboo Art",
        description: "Bamboo art in Samastipur, Bihar, focuses on eco-friendly, durable, and affordable products crafted by local artisans using generational techniques.",
        date: new Date(),
        location: "Samastipur, Bihar",
        category: "HandiCraft Product",
        totalAmount: 100,
        availableAmount: 100,
        productPrice: 200,
        image: "https://static.india.gov.in/npiprod/odop/uploads/bamboo_art_1e422027a3.jpg"
    },
    // Rahul 
    {
        title: "Medicinal Herbs",
        description: "Forest-grown herbs used in traditional and Ayurvedic medicine.",
        date: new Date(),
        location: "Sarangarh-Bilaigarh, Chhattisgarh",
        category: "Herbal",
        totalAmount: 1800,
        availableAmount: 1000,
        productPrice: 500,
        image: "https://cdn.mos.cms.futurecdn.net/vt3yrFpJxGeRSgYbCPjWaA.jpg"
    },

    {
        title: "Forest Honey",
        description: "Natural wild honey collected from forest areas with medicinal benefits.",
        date: new Date(),
        location: "Balrampur, Chhattisgarh",
        category: "Food",
        totalAmount: 1500,
        availableAmount: 900,
        productPrice: 400,
        image: "https://himalayatree.com/cdn/shop/products/1_cfb6c326-e819-4aac-8bc0-15b88912ef02_1200x1200.jpg?v=1623769228"
    },

    {
        title: "Tezpur Litchi",
        description: "Juicy litchi known for large pulp and sweetness.",
        date: new Date(),
        location: "Sonitpur, Assam",
        category: "Agriculture",
        totalAmount: 10000,
        availableAmount: 6000,
        productPrice: 100,
        image: "https://sahasa.in/wp-content/uploads/2021/02/tezpur_litchi_14.09.2020.jpg"
    },
    {
        title: "Areca Leaf Plates",
        description: "Eco-friendly disposable plates made from areca palm sheath.",
        date: new Date(),
        location: "Bongaigaon, Assam",
        category: "Eco Product",
        totalAmount: 100,
        availableAmount: 100,
        productPrice: 20,
        image: "https://daijiworld.ap-south-1.linodeobjects.com/Linode/images3/arecaplates_080625_1.jpg"
    },
    {
        title: "Idu Mishmi Shawl",
        description: "Colorful tribal shawl with geometric patterns representing Idu culture.",
        date: new Date(),
        location: "Dibang Valley, Arunachal Pradesh",
        category: "Handicraft",
        totalAmount: 300,
        availableAmount: 200,
        productPrice: 2200,
        image: "https://www.myindianproducts.com/images/gi_products/idu_mishmi_textiles_lower_dibang_valley.jpg",
    },
];

const seedDatabase = async () => {
    try {
        await mongoose.connect(process.env.MONGO_URI || 'mongodb://localhost:27017/Cluster0');
        console.log('\n✅ MongoDB connection open...');

        // Clear existing local products data for Maharashtra (Assuming category is NOT Heritage to avoid deleting heritage items if they share the same model and location structure. If they don't, this is fine.)
        // But to be safe and match the exact style of seedSouthProducts:
        // await Event.deleteMany({ location: /Maharashtra/i });
        // console.log('🗑️  Cleared existing data for Maharashtra.');

        const createdEvents = await Event.insertMany(events);
        console.log(`🎉 Created ${createdEvents.length} distinct district products from Maharashtra.`);

        console.log('\n🚀 Database seeded successfully!');
        process.exit();
    } catch (error) {
        console.error('❌ Error seeding data:', error);
        process.exit(1);
    }
};

seedDatabase();
